//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Language.FORM_BASIC {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_Fm_S001 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_Fm_S001() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WMS.Language.FORM_BASIC.Resource_Fm_S001", typeof(Resource_Fm_S001).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 新增部門/單位設定 的當地語系化字串。
        /// </summary>
        internal static string AddDialogTitle1 {
            get {
                return ResourceManager.GetString("AddDialogTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增角色權限設定 的當地語系化字串。
        /// </summary>
        internal static string AddDialogTitle2 {
            get {
                return ResourceManager.GetString("AddDialogTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增使用者資料-使用者帳號:{0}({1}) 的當地語系化字串。
        /// </summary>
        internal static string AddLog {
            get {
                return ResourceManager.GetString("AddLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增部門/單位資料-部門/單位代號:{0}({1}) 的當地語系化字串。
        /// </summary>
        internal static string AddLog1 {
            get {
                return ResourceManager.GetString("AddLog1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增角色權限資料-角色代號:{0}({1}) 的當地語系化字串。
        /// </summary>
        internal static string AddLog2 {
            get {
                return ResourceManager.GetString("AddLog2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確定要新增使用者資料嗎? 的當地語系化字串。
        /// </summary>
        internal static string AddMsgTitle {
            get {
                return ResourceManager.GetString("AddMsgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確定要新增部門/單位權限資料嗎? 的當地語系化字串。
        /// </summary>
        internal static string AddMsgTitle1 {
            get {
                return ResourceManager.GetString("AddMsgTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確定要新增角色權限資料嗎? 的當地語系化字串。
        /// </summary>
        internal static string AddMsgTitle2 {
            get {
                return ResourceManager.GetString("AddMsgTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增使用者資料設定成功 的當地語系化字串。
        /// </summary>
        internal static string AddSaveOk {
            get {
                return ResourceManager.GetString("AddSaveOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增部門/單位資料設定成功 的當地語系化字串。
        /// </summary>
        internal static string AddSaveOk1 {
            get {
                return ResourceManager.GetString("AddSaveOk1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增角色權限設定成功 的當地語系化字串。
        /// </summary>
        internal static string AddSaveOk2 {
            get {
                return ResourceManager.GetString("AddSaveOk2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除角色:{0}資料 的當地語系化字串。
        /// </summary>
        internal static string DeleteRoleLog {
            get {
                return ResourceManager.GetString("DeleteRoleLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除角色:{0}資料成功 的當地語系化字串。
        /// </summary>
        internal static string DeleteRoleOk {
            get {
                return ResourceManager.GetString("DeleteRoleOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除部門/單位:{0}資料 的當地語系化字串。
        /// </summary>
        internal static string DeleteUnitLog {
            get {
                return ResourceManager.GetString("DeleteUnitLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除部門/單位:{0}資料成功 的當地語系化字串。
        /// </summary>
        internal static string DeleteUnitOk {
            get {
                return ResourceManager.GetString("DeleteUnitOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 修改部門/單位設定 的當地語系化字串。
        /// </summary>
        internal static string EditDialogTitle1 {
            get {
                return ResourceManager.GetString("EditDialogTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 修改角色權限設定 的當地語系化字串。
        /// </summary>
        internal static string EditDialogTitle2 {
            get {
                return ResourceManager.GetString("EditDialogTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 修改使用者資料-使用者帳號:{0}({1}) 的當地語系化字串。
        /// </summary>
        internal static string EditLog {
            get {
                return ResourceManager.GetString("EditLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 修改部門/單位資料-部門/單位代號:{0}({1}) 的當地語系化字串。
        /// </summary>
        internal static string EditLog1 {
            get {
                return ResourceManager.GetString("EditLog1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 修改角色權限資料-角色代號:{0}({1}) 的當地語系化字串。
        /// </summary>
        internal static string EditLog2 {
            get {
                return ResourceManager.GetString("EditLog2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確定要修改使用者資料嗎? 的當地語系化字串。
        /// </summary>
        internal static string EditMsgTitle {
            get {
                return ResourceManager.GetString("EditMsgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確定要修改部門/單位資料嗎? 的當地語系化字串。
        /// </summary>
        internal static string EditMsgTitle1 {
            get {
                return ResourceManager.GetString("EditMsgTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確定要修改角色權限資料嗎? 的當地語系化字串。
        /// </summary>
        internal static string EditMsgTitle2 {
            get {
                return ResourceManager.GetString("EditMsgTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 修改使用者資料設定成功 的當地語系化字串。
        /// </summary>
        internal static string EditSaveOk {
            get {
                return ResourceManager.GetString("EditSaveOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 修改部門/單位資料設定成功 的當地語系化字串。
        /// </summary>
        internal static string EditSaveOk1 {
            get {
                return ResourceManager.GetString("EditSaveOk1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 修改角色權限設定成功 的當地語系化字串。
        /// </summary>
        internal static string EditSaveOk2 {
            get {
                return ResourceManager.GetString("EditSaveOk2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 訊息 的當地語系化字串。
        /// </summary>
        internal static string MsgTitle {
            get {
                return ResourceManager.GetString("MsgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 必要欄位，不可為空值 的當地語系化字串。
        /// </summary>
        internal static string Notnull {
            get {
                return ResourceManager.GetString("Notnull", resourceCulture);
            }
        }
    }
}
