//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Language.FORM_BASIC {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_Fm_B001 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_Fm_B001() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WMS.Language.FORM_BASIC.Resource_Fm_B001", typeof(Resource_Fm_B001).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 確定要新增物料基本資料嗎? 的當地語系化字串。
        /// </summary>
        internal static string AddDialogSaveMsg {
            get {
                return ResourceManager.GetString("AddDialogSaveMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增物料基本資料 的當地語系化字串。
        /// </summary>
        internal static string AddDialogTitle {
            get {
                return ResourceManager.GetString("AddDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增物料基本檔資料-物料代號:{0}({1}) 的當地語系化字串。
        /// </summary>
        internal static string AddLog {
            get {
                return ResourceManager.GetString("AddLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確定要刪除選取的物料基本檔資料?{0}物料代號:{1}({2}) 的當地語系化字串。
        /// </summary>
        internal static string DeleteConfirmMessage {
            get {
                return ResourceManager.GetString("DeleteConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除物料基本檔資料-物料代號:{0}({1}) 的當地語系化字串。
        /// </summary>
        internal static string DeleteLog {
            get {
                return ResourceManager.GetString("DeleteLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確定要修改物料: {0} [{1} ]的基本資料嗎? 的當地語系化字串。
        /// </summary>
        internal static string EditDialogSaveMsg {
            get {
                return ResourceManager.GetString("EditDialogSaveMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 修改物料基本資料 的當地語系化字串。
        /// </summary>
        internal static string EditDialogTitle {
            get {
                return ResourceManager.GetString("EditDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 修改物料基本檔資料-物料代號:{0}, 物料名稱:{1}-&gt;{2}, 庫存單位:{3}-&gt;{4}, 規格:{5}-&gt;{6}, 滿板數量:{7}-&gt;{8}, 儲位存放類型:{9}-&gt;{10} 的當地語系化字串。
        /// </summary>
        internal static string EditLog {
            get {
                return ResourceManager.GetString("EditLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 物料基本資料 的當地語系化字串。
        /// </summary>
        internal static string ExcellFilename {
            get {
                return ResourceManager.GetString("ExcellFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 物料代號:{0}，已建檔，請勿重複建檔 的當地語系化字串。
        /// </summary>
        internal static string Exist {
            get {
                return ResourceManager.GetString("Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 訊息 的當地語系化字串。
        /// </summary>
        internal static string MsgTitle {
            get {
                return ResourceManager.GetString("MsgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 必要欄位，不可為空值 的當地語系化字串。
        /// </summary>
        internal static string Notnull {
            get {
                return ResourceManager.GetString("Notnull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料筆數: {0}/{1} 的當地語系化字串。
        /// </summary>
        internal static string S0001 {
            get {
                return ResourceManager.GetString("S0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 物料主檔有此單位「{0}」，無法刪除。 的當地語系化字串。
        /// </summary>
        internal static string S0002 {
            get {
                return ResourceManager.GetString("S0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除失敗: 的當地語系化字串。
        /// </summary>
        internal static string S0005 {
            get {
                return ResourceManager.GetString("S0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 物料代號: {0}已被使用於庫存中，無法刪除。 的當地語系化字串。
        /// </summary>
        internal static string S0006 {
            get {
                return ResourceManager.GetString("S0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 物料代號: {0}尚有作業中工作檔，無法刪除。 的當地語系化字串。
        /// </summary>
        internal static string S0007 {
            get {
                return ResourceManager.GetString("S0007", resourceCulture);
            }
        }
    }
}
