//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.9151
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Language.FORM_ASRS {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_Fm_A002 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_Fm_A002() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WMS.Language.FORM_ASRS.Resource_Fm_A002", typeof(Resource_Fm_A002).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 取物 的當地語系化字串。
        /// </summary>
        internal static string Action1 {
            get {
                return ResourceManager.GetString("Action1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 置物 的當地語系化字串。
        /// </summary>
        internal static string Action2 {
            get {
                return ResourceManager.GetString("Action2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 移動 的當地語系化字串。
        /// </summary>
        internal static string Action3 {
            get {
                return ResourceManager.GetString("Action3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 庫間移載 的當地語系化字串。
        /// </summary>
        internal static string Action4 {
            get {
                return ResourceManager.GetString("Action4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確定要針對選取的吊車執行「禁用設定」嗎? 的當地語系化字串。
        /// </summary>
        internal static string ConfirmMessage {
            get {
                return ResourceManager.GetString("ConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確定要針對選取的吊車執行「異常復歸」嗎? 的當地語系化字串。
        /// </summary>
        internal static string ConfirmMessage1 {
            get {
                return ResourceManager.GetString("ConfirmMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確定要針對選取的吊車執行「{0}」嗎? 的當地語系化字串。
        /// </summary>
        internal static string ConfirmMessage2 {
            get {
                return ResourceManager.GetString("ConfirmMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 庫位 的當地語系化字串。
        /// </summary>
        internal static string DeviceType1 {
            get {
                return ResourceManager.GetString("DeviceType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 PD站 的當地語系化字串。
        /// </summary>
        internal static string DeviceType2 {
            get {
                return ResourceManager.GetString("DeviceType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 吊車異常記錄表 的當地語系化字串。
        /// </summary>
        internal static string ExcellFilename {
            get {
                return ResourceManager.GetString("ExcellFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請先勾選要設定的吊車 的當地語系化字串。
        /// </summary>
        internal static string Msg0001 {
            get {
                return ResourceManager.GetString("Msg0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請先勾選要執行異常復歸的吊車 的當地語系化字串。
        /// </summary>
        internal static string Msg0002 {
            get {
                return ResourceManager.GetString("Msg0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 吊車異常復歸一次僅能針對一台吊車執行 的當地語系化字串。
        /// </summary>
        internal static string Msg0003 {
            get {
                return ResourceManager.GetString("Msg0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選取來源位置 的當地語系化字串。
        /// </summary>
        internal static string Msg0004 {
            get {
                return ResourceManager.GetString("Msg0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選取目的位置 的當地語系化字串。
        /// </summary>
        internal static string Msg0005 {
            get {
                return ResourceManager.GetString("Msg0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 吊車非禁用狀態，無法執行手動控制命令 的當地語系化字串。
        /// </summary>
        internal static string Msg0006 {
            get {
                return ResourceManager.GetString("Msg0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請先勾選要執行吊車續行的吊車 的當地語系化字串。
        /// </summary>
        internal static string Msg0007 {
            get {
                return ResourceManager.GetString("Msg0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 吊車續行一次僅能針對一台吊車執行 的當地語系化字串。
        /// </summary>
        internal static string Msg0008 {
            get {
                return ResourceManager.GetString("Msg0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 手動控制一次僅能針對一台吊車執行 的當地語系化字串。
        /// </summary>
        internal static string Msg0009 {
            get {
                return ResourceManager.GetString("Msg0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 提示訊息 的當地語系化字串。
        /// </summary>
        internal static string MsgTitle {
            get {
                return ResourceManager.GetString("MsgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 儲存成功 的當地語系化字串。
        /// </summary>
        internal static string SaveOK {
            get {
                return ResourceManager.GetString("SaveOK", resourceCulture);
            }
        }
    }
}
