//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.9151
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Language.FORM_CHECK {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_Fm_C003 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_Fm_C003() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WMS.Language.FORM_CHECK.Resource_Fm_C003", typeof(Resource_Fm_C003).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 盤點差異資料 的當地語系化字串。
        /// </summary>
        internal static string ExcellFilename {
            get {
                return ResourceManager.GetString("ExcellFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 成品/原物料 的當地語系化字串。
        /// </summary>
        internal static string PROD_TYPE_0 {
            get {
                return ResourceManager.GetString("PROD_TYPE_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 載具 的當地語系化字串。
        /// </summary>
        internal static string PROD_TYPE_1 {
            get {
                return ResourceManager.GetString("PROD_TYPE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 先入品 的當地語系化字串。
        /// </summary>
        internal static string PROD_TYPE_2 {
            get {
                return ResourceManager.GetString("PROD_TYPE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 未檢 的當地語系化字串。
        /// </summary>
        internal static string QCResult0 {
            get {
                return ResourceManager.GetString("QCResult0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 合格 的當地語系化字串。
        /// </summary>
        internal static string QCResult1 {
            get {
                return ResourceManager.GetString("QCResult1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 不合格 的當地語系化字串。
        /// </summary>
        internal static string QCResult2 {
            get {
                return ResourceManager.GetString("QCResult2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 劣品 的當地語系化字串。
        /// </summary>
        internal static string QCResult3 {
            get {
                return ResourceManager.GetString("QCResult3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 良品 的當地語系化字串。
        /// </summary>
        internal static string QCResult4 {
            get {
                return ResourceManager.GetString("QCResult4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 待退 的當地語系化字串。
        /// </summary>
        internal static string QCResult5 {
            get {
                return ResourceManager.GetString("QCResult5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 待驗庫存 的當地語系化字串。
        /// </summary>
        internal static string StusCtr1 {
            get {
                return ResourceManager.GetString("StusCtr1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 可用庫存 的當地語系化字串。
        /// </summary>
        internal static string StusCtr2 {
            get {
                return ResourceManager.GetString("StusCtr2", resourceCulture);
            }
        }
    }
}
