//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.9151
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Language.FORM_OUT {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_Fm_O001 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_Fm_O001() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WMS.Language.FORM_OUT.Resource_Fm_O001", typeof(Resource_Fm_O001).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 確定要新增單據資料嗎? 的當地語系化字串。
        /// </summary>
        internal static string ConfirmAddMessage {
            get {
                return ResourceManager.GetString("ConfirmAddMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確定要將單據資料強制結單嗎? 的當地語系化字串。
        /// </summary>
        internal static string ConfirmCompleteMessage {
            get {
                return ResourceManager.GetString("ConfirmCompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確定要編輯單據資料嗎? 的當地語系化字串。
        /// </summary>
        internal static string ConfirmEditMessage {
            get {
                return ResourceManager.GetString("ConfirmEditMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確定要刪除單據資料嗎? 的當地語系化字串。
        /// </summary>
        internal static string ConfirmMessage {
            get {
                return ResourceManager.GetString("ConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 出庫單據資料 的當地語系化字串。
        /// </summary>
        internal static string ExcellFilename {
            get {
                return ResourceManager.GetString("ExcellFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 尚未新增任何單據明細，無法儲存 的當地語系化字串。
        /// </summary>
        internal static string Msg0001 {
            get {
                return ResourceManager.GetString("Msg0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 項次{0}, 尚未選取料號，無法儲存 的當地語系化字串。
        /// </summary>
        internal static string Msg0002 {
            get {
                return ResourceManager.GetString("Msg0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 項次{0}, 數量不可&lt;=0 的當地語系化字串。
        /// </summary>
        internal static string Msg0003 {
            get {
                return ResourceManager.GetString("Msg0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 單據狀態非接單或完成狀態，無法刪除單據資料 的當地語系化字串。
        /// </summary>
        internal static string Msg0004 {
            get {
                return ResourceManager.GetString("Msg0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 單號{0}, 項次{1}, 已被刪除, 請重新查詢確認 的當地語系化字串。
        /// </summary>
        internal static string Msg0005 {
            get {
                return ResourceManager.GetString("Msg0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 單據狀態非接單狀態，無法編輯單據資料 的當地語系化字串。
        /// </summary>
        internal static string Msg0006 {
            get {
                return ResourceManager.GetString("Msg0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 單據狀態非接單或出庫中狀態，無法強制結單 的當地語系化字串。
        /// </summary>
        internal static string Msg0007 {
            get {
                return ResourceManager.GetString("Msg0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 單據尚有作業中數量，無法強制結單 的當地語系化字串。
        /// </summary>
        internal static string Msg0008 {
            get {
                return ResourceManager.GetString("Msg0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 提示訊息 的當地語系化字串。
        /// </summary>
        internal static string MsgTitle {
            get {
                return ResourceManager.GetString("MsgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 單號不可為空值 的當地語系化字串。
        /// </summary>
        internal static string Notnull {
            get {
                return ResourceManager.GetString("Notnull", resourceCulture);
            }
        }
    }
}
