//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.9151
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Language {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_Public {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_Public() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WMS.Language.Resource_Public", typeof(Resource_Public).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 未啟動 的當地語系化字串。
        /// </summary>
        internal static string BcrStatus0 {
            get {
                return ResourceManager.GetString("BcrStatus0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 作業中 的當地語系化字串。
        /// </summary>
        internal static string BcrStatus1 {
            get {
                return ResourceManager.GetString("BcrStatus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已完成 的當地語系化字串。
        /// </summary>
        internal static string BcrStatus2 {
            get {
                return ResourceManager.GetString("BcrStatus2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 離開 的當地語系化字串。
        /// </summary>
        internal static string btnExit {
            get {
                return ResourceManager.GetString("btnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 登出 的當地語系化字串。
        /// </summary>
        internal static string btnLogout {
            get {
                return ResourceManager.GetString("btnLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 客戶代號 的當地語系化字串。
        /// </summary>
        internal static string colOrgNo {
            get {
                return ResourceManager.GetString("colOrgNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 物料描述 的當地語系化字串。
        /// </summary>
        internal static string colProdName {
            get {
                return ResourceManager.GetString("colProdName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 料號 的當地語系化字串。
        /// </summary>
        internal static string colProdNo {
            get {
                return ResourceManager.GetString("colProdNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 物料類型 的當地語系化字串。
        /// </summary>
        internal static string colProdType {
            get {
                return ResourceManager.GetString("colProdType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 客戶 的當地語系化字串。
        /// </summary>
        internal static string colSname {
            get {
                return ResourceManager.GetString("colSname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 單位 的當地語系化字串。
        /// </summary>
        internal static string colUnits {
            get {
                return ResourceManager.GetString("colUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 連線 的當地語系化字串。
        /// </summary>
        internal static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 修改前 的當地語系化字串。
        /// </summary>
        internal static string CYCD_FLAG0 {
            get {
                return ResourceManager.GetString("CYCD_FLAG0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 修改後 的當地語系化字串。
        /// </summary>
        internal static string CYCD_FLAG1 {
            get {
                return ResourceManager.GetString("CYCD_FLAG1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 庫存已被異動，請重新查詢確認 的當地語系化字串。
        /// </summary>
        internal static string CycdMsg001 {
            get {
                return ResourceManager.GetString("CycdMsg001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除成功 的當地語系化字串。
        /// </summary>
        internal static string DeleteOK {
            get {
                return ResourceManager.GetString("DeleteOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 離線 的當地語系化字串。
        /// </summary>
        internal static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 一般 的當地語系化字串。
        /// </summary>
        internal static string Emerge1 {
            get {
                return ResourceManager.GetString("Emerge1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 低 的當地語系化字串。
        /// </summary>
        internal static string Emerge2 {
            get {
                return ResourceManager.GetString("Emerge2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 中 的當地語系化字串。
        /// </summary>
        internal static string Emerge3 {
            get {
                return ResourceManager.GetString("Emerge3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 高 的當地語系化字串。
        /// </summary>
        internal static string Emerge4 {
            get {
                return ResourceManager.GetString("Emerge4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 入庫單據 的當地語系化字串。
        /// </summary>
        internal static string ListCtr1 {
            get {
                return ResourceManager.GetString("ListCtr1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 出庫單據 的當地語系化字串。
        /// </summary>
        internal static string ListCtr2 {
            get {
                return ResourceManager.GetString("ListCtr2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 查無異常工作檔「{0}」資料，無法執行吊車續行 的當地語系化字串。
        /// </summary>
        internal static string NoErrorTrk {
            get {
                return ResourceManager.GetString("NoErrorTrk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選取客戶代號 的當地語系化字串。
        /// </summary>
        internal static string OrgNoNullText {
            get {
                return ResourceManager.GetString("OrgNoNullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 單號:{0}, 項次:{1}, 查無入庫單據資料, 請重新查詢確認 的當地語系化字串。
        /// </summary>
        internal static string PalletInMsg001 {
            get {
                return ResourceManager.GetString("PalletInMsg001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 單號:{0}, 項次:{1}, 單據狀態非接單或收料中, 無法執行組盤作業 的當地語系化字串。
        /// </summary>
        internal static string PalletInMsg002 {
            get {
                return ResourceManager.GetString("PalletInMsg002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 單號:{0}, 項次:{1}, 單據可組盤量不足, 無法執行組盤作業 的當地語系化字串。
        /// </summary>
        internal static string PalletInMsg003 {
            get {
                return ResourceManager.GetString("PalletInMsg003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 成品/原物料 的當地語系化字串。
        /// </summary>
        internal static string PROD_TYPE_0 {
            get {
                return ResourceManager.GetString("PROD_TYPE_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 載具 的當地語系化字串。
        /// </summary>
        internal static string PROD_TYPE_1 {
            get {
                return ResourceManager.GetString("PROD_TYPE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 先入品 的當地語系化字串。
        /// </summary>
        internal static string PROD_TYPE_2 {
            get {
                return ResourceManager.GetString("PROD_TYPE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選取料號 的當地語系化字串。
        /// </summary>
        internal static string ProdNoNullText {
            get {
                return ResourceManager.GetString("ProdNoNullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 未檢 的當地語系化字串。
        /// </summary>
        internal static string QC0 {
            get {
                return ResourceManager.GetString("QC0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 合格 的當地語系化字串。
        /// </summary>
        internal static string QC1 {
            get {
                return ResourceManager.GetString("QC1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 不合格 的當地語系化字串。
        /// </summary>
        internal static string QC2 {
            get {
                return ResourceManager.GetString("QC2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 良品 的當地語系化字串。
        /// </summary>
        internal static string QC3 {
            get {
                return ResourceManager.GetString("QC3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 劣品 的當地語系化字串。
        /// </summary>
        internal static string QC4 {
            get {
                return ResourceManager.GetString("QC4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 待退 的當地語系化字串。
        /// </summary>
        internal static string QC5 {
            get {
                return ResourceManager.GetString("QC5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 未回報 的當地語系化字串。
        /// </summary>
        internal static string REPLY_FLG0 {
            get {
                return ResourceManager.GetString("REPLY_FLG0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已回報 的當地語系化字串。
        /// </summary>
        internal static string REPLY_FLG1 {
            get {
                return ResourceManager.GetString("REPLY_FLG1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 先進先出 的當地語系化字串。
        /// </summary>
        internal static string ShippingStrategy1 {
            get {
                return ResourceManager.GetString("ShippingStrategy1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 最少板數 的當地語系化字串。
        /// </summary>
        internal static string ShippingStrategy2 {
            get {
                return ResourceManager.GetString("ShippingStrategy2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 接單 的當地語系化字串。
        /// </summary>
        internal static string StatusCtr0 {
            get {
                return ResourceManager.GetString("StatusCtr0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 出庫中 的當地語系化字串。
        /// </summary>
        internal static string StatusCtr33 {
            get {
                return ResourceManager.GetString("StatusCtr33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 收料中 的當地語系化字串。
        /// </summary>
        internal static string StatusCtr8 {
            get {
                return ResourceManager.GetString("StatusCtr8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 完成 的當地語系化字串。
        /// </summary>
        internal static string StatusCtr90 {
            get {
                return ResourceManager.GetString("StatusCtr90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 強制結單 的當地語系化字串。
        /// </summary>
        internal static string StatusCtr98 {
            get {
                return ResourceManager.GetString("StatusCtr98", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 手動觸發強制結單 的當地語系化字串。
        /// </summary>
        internal static string StatusCtr99 {
            get {
                return ResourceManager.GetString("StatusCtr99", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 儲存成功 的當地語系化字串。
        /// </summary>
        internal static string SubmitOK {
            get {
                return ResourceManager.GetString("SubmitOK", resourceCulture);
            }
        }
    }
}
