//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.9151
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Language {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_fm_Login {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_fm_Login() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WMS.Language.Resource_fm_Login", typeof(Resource_fm_Login).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 請輸入帳號 的當地語系化字串。
        /// </summary>
        internal static string Msg001 {
            get {
                return ResourceManager.GetString("Msg001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請輸入密碼 的當地語系化字串。
        /// </summary>
        internal static string Msg002 {
            get {
                return ResourceManager.GetString("Msg002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 查詢使用者資料異常:{0} 的當地語系化字串。
        /// </summary>
        internal static string Msg003 {
            get {
                return ResourceManager.GetString("Msg003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 查無使用者帳號，請確認帳號輸入是否正確 的當地語系化字串。
        /// </summary>
        internal static string Msg004 {
            get {
                return ResourceManager.GetString("Msg004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 該帳號已停用 的當地語系化字串。
        /// </summary>
        internal static string Msg005 {
            get {
                return ResourceManager.GetString("Msg005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密碼錯誤 的當地語系化字串。
        /// </summary>
        internal static string Msg006 {
            get {
                return ResourceManager.GetString("Msg006", resourceCulture);
            }
        }
    }
}
