//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Language {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_WMS_STK {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_WMS_STK() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WMS.Language.Resource_WMS_STK", typeof(Resource_WMS_STK).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 新增成功 的當地語系化字串。
        /// </summary>
        internal static string AddOK {
            get {
                return ResourceManager.GetString("AddOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除成功 的當地語系化字串。
        /// </summary>
        internal static string DeleteOK {
            get {
                return ResourceManager.GetString("DeleteOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 修改成功 的當地語系化字串。
        /// </summary>
        internal static string EditOK {
            get {
                return ResourceManager.GetString("EditOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 未選取任何待驗庫存, 請選取後重新作業 的當地語系化字串。
        /// </summary>
        internal static string Msg0001 {
            get {
                return ResourceManager.GetString("Msg0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 倉庫:{0},庫位:{1},料號:{2}非待驗庫存, 無法執行質檢結果輸入, 請重新查詢確認  的當地語系化字串。
        /// </summary>
        internal static string Msg0002 {
            get {
                return ResourceManager.GetString("Msg0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 未選取任何庫存, 請選取後重新作業 的當地語系化字串。
        /// </summary>
        internal static string Msg0003 {
            get {
                return ResourceManager.GetString("Msg0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 倉庫:{0},庫位:{1},料號:{2}已被其他作業預約, 無法執行刪除庫存, 請重新查詢確認 的當地語系化字串。
        /// </summary>
        internal static string Msg0004 {
            get {
                return ResourceManager.GetString("Msg0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 庫位:{0} 非空庫位, 無法新增庫存資料 的當地語系化字串。
        /// </summary>
        internal static string Msg0005 {
            get {
                return ResourceManager.GetString("Msg0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 輸入的庫存資料有不同物料類型, 不同物料類型貨物不能混放在同個庫位, 請重新輸入 的當地語系化字串。
        /// </summary>
        internal static string Msg0006 {
            get {
                return ResourceManager.GetString("Msg0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 庫位:{0} 非庫存庫位, 無法修改庫存資料 的當地語系化字串。
        /// </summary>
        internal static string Msg0007 {
            get {
                return ResourceManager.GetString("Msg0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 成品/原物料 的當地語系化字串。
        /// </summary>
        internal static string PROD_TYPE_0 {
            get {
                return ResourceManager.GetString("PROD_TYPE_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 載具 的當地語系化字串。
        /// </summary>
        internal static string PROD_TYPE_1 {
            get {
                return ResourceManager.GetString("PROD_TYPE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 先入品 的當地語系化字串。
        /// </summary>
        internal static string PROD_TYPE_2 {
            get {
                return ResourceManager.GetString("PROD_TYPE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 未檢 的當地語系化字串。
        /// </summary>
        internal static string QC0 {
            get {
                return ResourceManager.GetString("QC0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 合格 的當地語系化字串。
        /// </summary>
        internal static string QC1 {
            get {
                return ResourceManager.GetString("QC1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 不合格 的當地語系化字串。
        /// </summary>
        internal static string QC2 {
            get {
                return ResourceManager.GetString("QC2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 良品 的當地語系化字串。
        /// </summary>
        internal static string QC3 {
            get {
                return ResourceManager.GetString("QC3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 劣品 的當地語系化字串。
        /// </summary>
        internal static string QC4 {
            get {
                return ResourceManager.GetString("QC4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 待退 的當地語系化字串。
        /// </summary>
        internal static string QC5 {
            get {
                return ResourceManager.GetString("QC5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 質檢結果輸入完成 的當地語系化字串。
        /// </summary>
        internal static string QCResultInputOK {
            get {
                return ResourceManager.GetString("QCResultInputOK", resourceCulture);
            }
        }
    }
}
