//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Language {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_WCS_TRK {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_WCS_TRK() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WMS.Language.Resource_WCS_TRK", typeof(Resource_WCS_TRK).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 {0}號倉 的當地語系化字串。
        /// </summary>
        internal static string AsrsIDItems {
            get {
                return ResourceManager.GetString("AsrsIDItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0}號 的當地語系化字串。
        /// </summary>
        internal static string CrnItems {
            get {
                return ResourceManager.GetString("CrnItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料庫異動筆數錯誤，異動筆數:{0} 的當地語系化字串。
        /// </summary>
        internal static string EffectRowsError {
            get {
                return ResourceManager.GetString("EffectRowsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 參數AsrsID為不合法的ASRS_ID(需&gt;0) 的當地語系化字串。
        /// </summary>
        internal static string Msg0001 {
            get {
                return ResourceManager.GetString("Msg0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 入庫板數不可為空值 的當地語系化字串。
        /// </summary>
        internal static string Msg0002 {
            get {
                return ResourceManager.GetString("Msg0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 參數DevNo(站台編號)不可為空值 的當地語系化字串。
        /// </summary>
        internal static string Msg0003 {
            get {
                return ResourceManager.GetString("Msg0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 參數Stks不可為null 的當地語系化字串。
        /// </summary>
        internal static string Msg0004 {
            get {
                return ResourceManager.GetString("Msg0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 參數Stks筆數為0, 不需出庫 的當地語系化字串。
        /// </summary>
        internal static string Msg0005 {
            get {
                return ResourceManager.GetString("Msg0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 參數出庫站台編號(DevNo) 為空值，不可出庫。 的當地語系化字串。
        /// </summary>
        internal static string Msg0006 {
            get {
                return ResourceManager.GetString("Msg0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 選取的庫存資料已被異動，請重新查詢確認 的當地語系化字串。
        /// </summary>
        internal static string Msg0007 {
            get {
                return ResourceManager.GetString("Msg0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 庫位:{0}, 庫存狀態:{1}, 非在庫庫存, 請重新查詢確認 的當地語系化字串。
        /// </summary>
        internal static string Msg0008 {
            get {
                return ResourceManager.GetString("Msg0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 參數OutLines不可為null 的當地語系化字串。
        /// </summary>
        internal static string Msg0009 {
            get {
                return ResourceManager.GetString("Msg0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 參數OutLines筆數為0, 不需出庫 的當地語系化字串。
        /// </summary>
        internal static string Msg0010 {
            get {
                return ResourceManager.GetString("Msg0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 單號:{0}, 項次:{1}, 本次出庫量不可&lt;=0 的當地語系化字串。
        /// </summary>
        internal static string Msg0011 {
            get {
                return ResourceManager.GetString("Msg0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 單號:{0}, 項次:{1}, 可用庫存不足 的當地語系化字串。
        /// </summary>
        internal static string Msg0012 {
            get {
                return ResourceManager.GetString("Msg0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 參數BinStas不可為null 的當地語系化字串。
        /// </summary>
        internal static string Msg0013 {
            get {
                return ResourceManager.GetString("Msg0013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 參數BinStas筆數為0, 不需出庫 的當地語系化字串。
        /// </summary>
        internal static string Msg0014 {
            get {
                return ResourceManager.GetString("Msg0014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 庫位:{0}, 庫存狀態:{1}, 非先入品庫存, 請重新查詢確認 的當地語系化字串。
        /// </summary>
        internal static string Msg0015 {
            get {
                return ResourceManager.GetString("Msg0015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 參數InLines不可為null 的當地語系化字串。
        /// </summary>
        internal static string Msg0016 {
            get {
                return ResourceManager.GetString("Msg0016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 參數InLines筆數為0, 不需出庫 的當地語系化字串。
        /// </summary>
        internal static string Msg0017 {
            get {
                return ResourceManager.GetString("Msg0017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 選取的單號:{0}, 項次:{1}, 入庫量不可&lt;=0 的當地語系化字串。
        /// </summary>
        internal static string Msg0018 {
            get {
                return ResourceManager.GetString("Msg0018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 派令成功 的當地語系化字串。
        /// </summary>
        internal static string SubmitOK {
            get {
                return ResourceManager.GetString("SubmitOK", resourceCulture);
            }
        }
    }
}
